# Generated by Django 3.1.4 on 2021-01-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trt',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to='profile', verbose_name='Image : '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price : '),
        ),
    ]
